# Generated by Django 2.2.4 on 2020-03-08 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200308_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='misc',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
